### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by helsien** [maykar/plex_assistant#45] opened 2020-09-07 11:38 UTC
Plex assistant can't be installed.
plex_assistant:
  url: 'http://192.168.1.3:32400'
  token: 'placed my token here'

**Comment by maykar** [comment] 2020-09-07 15:30
How did you try to install? Do you get any errors? Is that your URL (I ask since that is also the URL used in the example)? Is that exactly how you placed your config in configuration.yaml? Because it's missing indentation:

```
plex_assistant:
  url: 'http://192.168.1.3:32400'
  token: 'tH1s1Sy0uRT0k3n'
```

**Comment by maykar** [comment] 2020-09-07 18:40
Closing as invalid as there is not enough information to even guess what the issue is here.

**Closed by maykar** 2020-09-07 18:40 UTC
Labels: invalid
