### ISSUE TITLE
Plex Managed Users Support

### ISSUE THREAD

**Issue by zhdenny** [maykar/plex_assistant#61] opened 2020-10-18 16:20 UTC
I know you already addressed adding multiple Plex Account support.
https://github.com/maykar/plex_assistant/issues/17

But.....what about Plex Managed User Suppport? All my users are under One single Plex account (my account). Plex supports multiple "managed users" in a single account. Can/Will plex_assistant support managed users?

**Comment by maykar** [comment] 2020-10-18 16:26
Looks like you posted twice. Duplicate of #61

**Closed by maykar** 2020-10-18 16:26 UTC
