### ISSUE TITLE
Cast Device Not Found

### ISSUE THREAD

**Issue by undulattice** [maykar/plex_assistant#15] opened 2020-04-14 12:11 UTC
Hi.

I've gotten everything installed, webhooks received from IFTTT, and automation firing.
I'm getting the following error in the logs:

Logger: custom_components.plex_assistant
Source: custom_components/plex_assistant/__init__.py:117
First occurred: 12:44:33 PM (1 occurrences)
Last logged: 12:44:33 PM

Cast device not found.

Have tried multiple Plex clients (both name and IP) and Chromecast devices and same error with all of them.
What am I missing?!

Thanks

**Comment by dedepene** [comment] 2020-04-14 12:55
same here, although I went dialogwlof route, not IFTTT

> WARNING (SyncWorker_2) [custom_components.plex_assistant] Cast device not found.

**Comment by undulattice** [comment] 2020-04-14 13:33
Forgot to include config:

plex_assistant:
  url: 'http://192.168.2.250:32400'
  token: 'MYTOKENHERE'
  default_cast: 'MacMini'
  language: 'en'
  tts_errors: true

**Comment by undulattice** [comment] 2020-04-15 03:08
Success! :-)

So I added the Plex integration which allowed HA to add my Plex Media Player as a mediaplayer entity.
Added the mediaplayer entity name as an alias in the plex_assistant config and bam!

So here's the finished config I'm using. Hope it helps.

plex_assistant:
  url: 'http://192.168.2.250:32400'
  token: 'MYTOKEN'
  default_cast: 'MacMini'
  language: 'en'
  tts_errors: true
  aliases:
    MacMini: plex_plex_media_player_macmini

**Comment by dedepene** [comment] 2020-04-15 08:05
OK, there's some progress. With your tip I can now actually play something, but it's mostly a hit or miss. Sometimes it would play the wrong thing, and other times it would process the command but nothing happens, especially if there's something already being played on the same chromecast.

Do you get this a lot?

`INFO (SyncWorker_5) [pychromecast.controllers] Not launching app 9AC194DC - already running`

**Comment by undulattice** [comment] 2020-04-15 10:56
I've not tested it properly yet. Got it running late last night. Will investigate.
My main problem is the delay between sending the command and getting a response, even when running the plex_asssistant.command from the developer tools.

Are you seeing a delay?

I'm not seeing any errors, though I'm casting to a Plex Client and not to a Chromecast.
I suspect "app 9AC194DC" refers to the Plex app on the Chromecast though. If so, then nothing to worry about.

**Comment by karl0ss** [comment] 2020-05-06 08:30
Im getting the same thing, And I have tried your tip about the entity, but am still getting the same issue :(

**Comment by maykar** [comment] 2020-05-24 03:34
Using the URL below after adding in your info should give you the name of your connected devices:

`<PLEX ADDRESS>:32400/applications/Cast/clients?X-Plex-Token=<PLEX TOKEN>`

**Comment by karl0ss** [comment] 2020-05-26 08:20
`http://192.168.4.5:32400/applications/Cast/clients?X-Plex-Token=<MyTOKEN>`

Provides me with 404 not found

**Comment by maykar** [comment] 2020-05-26 11:26
Can try these as well:

`http://[plexIPaddress]:32400/applications/Cast/resources?X-Plex-Token=[yourToken]`

`http://[plexIPaddress]:32400/applications/Cast/devices?X-Plex-Token=[yourToken]`

**Comment by maykar** [comment] 2020-05-26 11:29
If the device is a smart TV or similar, make sure that the Plex app is open before checking.

**Comment by maykar** [comment] 2020-05-26 14:38
@karl0ss Let me know which URL works for you if any. I'm going to make my own feature request to display connected device names as an attribute of the sensor.

**Comment by TheOddball** [comment] 2020-06-12 09:28
Since OP decided to ghost on this, I'll try those links tomorrow morning as I can reproduce this exact issue.

**Comment by TheOddball** [comment] 2020-06-12 22:27
All of the links result in a 404

**Comment by maykar** [comment] 2020-06-13 15:41
No worries, I found a better way to do it. Next version will have a sensor that you can add that will list device names.

**Comment by maykar** [comment] 2020-06-17 17:15
Latest release adds the [Companion Sensor](https://github.com/maykar/plex_assistant#companion-sensor). See if the info it provides helps this issue.

**Comment by maykar** [comment] 2020-06-17 18:57
Going to close this one as the new sensor will help with knowing the name of the device that should be used (with or without creating an alias for it) and there were multiple things that may have been causing this issue that were addressed in the latest updates.

If you are still having these errors, please create a new issue. Thanks!

**Closed by maykar** 2020-06-17 18:57 UTC

**Comment by TheOddball** [comment] 2020-06-17 22:45
Still cannot find the device.

**Comment by maykar** [comment] 2020-06-17 23:15
So the device is shown in the sensor, but you get the "cast device not found error"?

If that's the case then maybe it's worth setting up an alias for your specific device since google could be interpreting that a different way.

```
  aliases:
    "second bedroom tv": "2nd Bedroom TV"
```

**Comment by TheOddball** [comment] 2020-06-17 23:18
Well hey, that worked, but now plex is erroring with "something went wrong"

**Comment by maykar** [comment] 2020-06-21 16:42
@TheOddball I have added the cast_delay config option in the latest release that may help with that. Take a look at the updated readme on how to use the option as well as test the amount of delay that will work for you.
