### ISSUE TITLE
Cannot request next episode or specific episode.

### ISSUE THREAD

**Issue by lifebound** [maykar/plex_assistant#38] opened 2020-08-13 16:38 UTC
Command: "Ask Plex to play next episode" or just "play next episode"

Expected behavior: Plex advances to next episode in order

Actual result: The first episode restarts.

**Comment by maykar** [comment] 2020-08-30 23:28
This is a limitation of 2 libraries that this project depends on, Pychromecast and Python-PlexAPI. Both of those projects have PRs on them to add the functionality needed to add this. Once they are pulled and added into HA I will add support for this.

**Comment by maykar** [comment] 2020-08-31 03:37
Marking this one as a duplicate of #36 

Once [Pychromecast adds queuing]https://github.com/home-assistant-libs/pychromecast/pull/404() of episodes and [PlexAPI adds continuous playing](https://github.com/pkkid/python-plexapi/pull/561) I'll add this in.

**Closed by maykar** 2020-08-31 03:37 UTC
Labels: duplicate
