### ISSUE TITLE
Can't get Google Assistant to Trigger with "Tell Plex"

### ISSUE THREAD

**Issue by exetico** [maykar/plex_assistant#66] opened 2020-11-07 14:36 UTC
Hi,

I've followed the guide step-by-step, and my test-app is working fine, if I try to use the "test" option, and start the "test"-version, too.

Therefore, I think everything is defined as it should, right? 

Expand "Responses" turn on “Set this intent as end of conversation”

![image](https://user-images.githubusercontent.com/3549445/98443576-66072300-210c-11eb-819b-75fa804edb84.png)

I've added both Danish and English.

By saying "Talk with Plex", I'm able to get it to start my test-app. Hereafter I'm able to give the command. But I've not been able to say "Hey Google, ask Plex to play the latest episode of XYZ" - I've also tried with "talk" and so on, but it doesn't help.

What have I done wrong?

On "Integrations", Plex is added in both boxes.

By testing it, and using the "Manage Assistant App", I'm able to add "Plex" too.
![image](https://user-images.githubusercontent.com/3549445/98443809-23464a80-210e-11eb-9537-62bc6e21d56a.png)

But... It doesn't help.

The only wierd thing I've found, is that "Plex" is lost from the "Implicit invocation" field, after the page has been reloaded:
![image](https://user-images.githubusercontent.com/3549445/98443827-512b8f00-210e-11eb-85ed-34d1eb2534d7.png)
Here's only the "Default Welcome Intent", if I click on the field.
![image](https://user-images.githubusercontent.com/3549445/98444661-37d91180-2113-11eb-95e2-20d9f18298f2.png)

But Plex is created as documented in the "Intents"-section:
![image](https://user-images.githubusercontent.com/3549445/98443854-7ae4b600-210e-11eb-8164-ce948ad419dd.png)
![image](https://user-images.githubusercontent.com/3549445/98443868-8e901c80-210e-11eb-8d8e-5371ed93a593.png)
![image](https://user-images.githubusercontent.com/3549445/98443883-9bad0b80-210e-11eb-8be0-94da032e2101.png)

Things I've tried:
- Remove the "Danish" Invocation-name, and only defined the english
- Started all over, with no luck.
- Webhook is working fine, as I've tested in the "test" section, where It's communication just fine by testing the test app.

**Comment by maykar** [comment] 2020-11-07 15:20
Unfortunately, I'm not sure what might be causing the issue. I just deleted mine and followed the instructions from the readme (didn't do anything else, just followed the instructions and closed all dialogflow windows) and everything is working as it should.

**Comment by exetico** [comment] 2020-11-07 16:04
Well.. I'll give it another try - and share screenshots too. Maybe that would be helpful for other people, too.

<hr>

1. Click on Create Agent and Type "Plex_Assistant" as the agent name and select "Create"

![image](https://user-images.githubusercontent.com/3549445/98445312-53deb200-2117-11eb-97e7-fe6e59f2704f.png)
![image](https://user-images.githubusercontent.com/3549445/98445324-6953dc00-2117-11eb-9961-5f9e0996de69.png)

_I've not selected a Google Project. Should I do that?_


2. Now select "Fulfillment" in the sidebar and enable "Webhook"

![image](https://user-images.githubusercontent.com/3549445/98445376-c64f9200-2117-11eb-8997-b7be4ecd9810.png)

3. Enter the "URL" Home Assistant provided us earlier, scroll down and click "Save"

![image](https://user-images.githubusercontent.com/3549445/98445381-d6677180-2117-11eb-86d5-ebb2bcde9d04.png)

4. Now select "Intents" in the sidebar and hit the "Create Intent" button.

![image](https://user-images.githubusercontent.com/3549445/98445409-f303a980-2117-11eb-9c29-2719b9b074d9.png)

5. Select "ADD PARAMETERS AND ACTION" and enter "Plex" as the action name.

![image](https://user-images.githubusercontent.com/3549445/98445418-0282f280-2118-11eb-9e10-f230e6435126.png)
![image](https://user-images.githubusercontent.com/3549445/98445433-10387800-2118-11eb-9044-2a54108135ff.png)


6. Check the checkbox under "Required"

![image](https://user-images.githubusercontent.com/3549445/98445443-1a5a7680-2118-11eb-9579-b60360fe9891.png)

7. Under "Parameter Name" put "command", under "Entity" put "@sys.any", and under "Value" put "$command"

![image](https://user-images.githubusercontent.com/3549445/98445461-33fbbe00-2118-11eb-9106-d1e1c6c6d490.png)

8. Now click "ADD TRAINING PHRASES"

![image](https://user-images.githubusercontent.com/3549445/98445472-3f4ee980-2118-11eb-854c-94568ba87fa2.png)

9.  Create a phrase and type in "command"

![image](https://user-images.githubusercontent.com/3549445/98445480-4b3aab80-2118-11eb-86b6-a2a943f88184.png)

10. Then double click on the word "command" you just entered and select "@sys.any:command"

![image](https://user-images.githubusercontent.com/3549445/98445504-60173f00-2118-11eb-8291-c00307f4e9c7.png)
![image](https://user-images.githubusercontent.com/3549445/98445511-66a5b680-2118-11eb-8726-15c84bc4c347.png)

11. Scroll to the bottom and expand "Fulfillment" then click "ENABLE FULFILLMENT"

![image](https://user-images.githubusercontent.com/3549445/98445530-7f15d100-2118-11eb-93ea-09e413ae406b.png)
![image](https://user-images.githubusercontent.com/3549445/98445544-876e0c00-2118-11eb-9877-2b98f9ac20f8.png)

12. Turn on "Enable webhook call for this intent"

![image](https://user-images.githubusercontent.com/3549445/98445559-948afb00-2118-11eb-9937-65733f9469c1.png)

13. Expand "Responses" turn on “Set this intent as end of conversation”

![image](https://user-images.githubusercontent.com/3549445/98445569-9ce33600-2118-11eb-9b16-e1429bb0bb69.png)
![image](https://user-images.githubusercontent.com/3549445/98445593-bc7a5e80-2118-11eb-9d4e-e0382b9f9738.png)


**THIS IS THE ONLY THING I'M A BIT UNSURE ABOUT. Should I add something to this part? Is do should I just secure that it's enabled?

14. At the top of the page enter "Plex" for the intent name and hit "Save"

![image](https://user-images.githubusercontent.com/3549445/98445615-e03da480-2118-11eb-95e4-9ef6f20d3e63.png)
![image](https://user-images.githubusercontent.com/3549445/98445630-ecc1fd00-2118-11eb-8b09-e895636e09b3.png)

15. On the left side of the page hit "Integrations", then "Integration Settings"

![image](https://user-images.githubusercontent.com/3549445/98445640-f9deec00-2118-11eb-8d48-c29eb89471ae.png)
![image](https://user-images.githubusercontent.com/3549445/98445652-0cf1bc00-2119-11eb-9cb6-13ffa3d096ec.png)

16. Click the space under "Explicit invocation", select "Plex"

![image](https://user-images.githubusercontent.com/3549445/98445661-19761480-2119-11eb-8e70-2333837055a6.png)

17, Type "Plex" in "Implicit invocation"

![image](https://user-images.githubusercontent.com/3549445/98445669-23981300-2119-11eb-98ea-2e4e922664d0.png)
![image](https://user-images.githubusercontent.com/3549445/98445684-41657800-2119-11eb-8db3-3ae266cf9f98.png)

18. You may need to hit the test button and accept terms of service before next step

![image](https://user-images.githubusercontent.com/3549445/98445689-49bdb300-2119-11eb-9640-3d1a382f3892.png)
![image](https://user-images.githubusercontent.com/3549445/98445694-4fb39400-2119-11eb-90bb-a449e4647a19.png)
![image](https://user-images.githubusercontent.com/3549445/98445716-7a055180-2119-11eb-8633-e30593c35c8f.png)

_I've tried to type something like 'Afspil senest afsnit af X' (Play latest epsiode of X), and it's working fine in Actions Console > Test._

19. Click "Manage assistant app"
![image](https://user-images.githubusercontent.com/3549445/98445775-d7999e00-2119-11eb-9f3a-0b70dd4b244e.png)

**Now "Plex" is missing form "Implicit invocation" agian**.... I'm **only** able to select the "Default Welcome Internt"?

_But I did try to type it manually:_
![image](https://user-images.githubusercontent.com/3549445/98445787-e54f2380-2119-11eb-9155-c288ccc7e201.png)


20. Then "Decide how your action is invoked", in the new Actions Console > Overview window.

![image](https://user-images.githubusercontent.com/3549445/98445809-ff890180-2119-11eb-81eb-9fe85daefb31.png)

21. Under "Display Name" type "Plex" then hit save in the top right (it may give an error, but thats okay).

![image](https://user-images.githubusercontent.com/3549445/98445823-0b74c380-211a-11eb-8a42-01185e82f336.png)
![image](https://user-images.githubusercontent.com/3549445/98445828-14659500-211a-11eb-9171-5b842189f1f3.png)

<hr>

It's provide me the info about the Plex-word, which I guess is the error you're referring to?

> Could not reserve your pronunciation 'Plex' because: Your Action's display name is, or sounds like, a reserved brand name. If you are affiliated with this brand, please visit the Connected Properties tab to verify your affiliation and claim the reserved brand name.

**At this point, everything should work as expected, right?**

But... "Plex" is lost from the "Implicit invocation" again:
![image](https://user-images.githubusercontent.com/3549445/98445856-5f7fa800-211a-11eb-8b98-30cca1d9c059.png)

I guess that's why it doesn't work? But I've not managed to save the string. If i select the "Default Welcome Intent", there's no problem - that string is saved just fine in the "Implicit invocation"-field. So it must be something with the configuration, cause "Plex" is not showing up as a suggestion.... or?

**Comment by exetico** [comment] 2020-11-07 16:14
![image](https://user-images.githubusercontent.com/3549445/98446177-0b75c300-211c-11eb-9d1d-b7e5168b7ea9.png)
My "Entities" is empty. That's not relevant, right? 

Are you doing something else, than mentioned in the step-by-step guide? There must be something? :-D 

If I'm saying "Talk with Plex" (in Danish), it's responding with "Recieved. I'm preparing the test version of Plex".

**Comment by exetico** [comment] 2020-11-07 16:15
Oh waow.. After tying a few times, now it's handling the request.

"Okay. I'm loading the test-version of Plex".

And... It's starting :-D!

**Are there any way to skip this part, so it's not talking about the "test-version of Plex"?

**Comment by maykar** [comment] 2020-11-08 17:19
Is it saying this when you speak the command "tell plex to..." or is that portion still not working for you?

**Comment by exetico** [comment] 2020-11-08 18:29
It's working with 'Hi Google. Tell Plex to...', but Google's answer is: 'I'm starting the test version of Plex', and after that, it's comfirms that the message is passed to HA, with 'Your request is delivered to Plex'.

I would just like to have the 'test' information removed, if possible. 

Aren't you hearing the same thing, after your command to Plex? 👍 

(All the things is in Danish, ofc...😀)

**Comment by maykar** [comment] 2020-11-08 18:43
I was fairly certain that it wasn't, but just recreated again and it most certainly is. Unfortunately, I think that the only way to get it to not make that statement would be to build and release as a full project, which is not something that you want to do as it's hook is connected to your HA system.

After a fair bit of searching and testing I haven't found a way around this and I'm not sure if this was something that has always been there or not as since I use IFTTT exclusively and only setup dialogflow when someone is having issues or needs an answer.

**Comment by maykar** [comment] 2020-11-08 19:00
Closing for now as expected behavior, but you'll be the first to know if a solution is found.

**Closed by maykar** 2020-11-08 19:00 UTC
